### ISSUE TITLE
能不能不带背景修改标题

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [PlayerMiller109/obsidian-keep-headings#2]
您好，您的插件真的很棒，ob块不具有连续性一直是困扰我的问题，但是因为您的插件这个问题得到了很好的解决。但是能不能修改标题时不要类似于弹出窗口，直接就修改原文档不好了（样式没变化，就像正常编辑一样），然后出个弹窗提示，您看看行不行，要不总误触。
### 容易误触
<img width="441" alt="image" src="https://github.com/user-attachments/assets/daa3d0b6-4afb-4074-a55c-947fdce48680">

### 直接修改行不行大佬
<img width="430" alt="image" src="https://github.com/user-attachments/assets/a7070959-c27c-450e-a3e5-d55ef3d59a63">

**Comment by shoudeyunkaijianyueming** [comment]
或者说弹出一个另一个样式修改标题，总感觉不踏实，误触

**Comment by PlayerMiller109** [comment]
这个只能等官方实现。毕竟官方目前自带的重命名标题就是写在弹窗里的，很难做到那种理想的效果。

**Comment by PlayerMiller109** [comment]
话说你截图的版本是最新版吗，0831 号更新的版本不再默认设置背景颜色了。如果想设置也可自行添加 CSS。

```css
.kh-bg {
  background: var(--background-modifier-cover);
}
```
