### ISSUE TITLE
Add ability to paste clipboard content into editor bar

### ISSUE THREAD

**Issue by zanodor** [PlayerMiller109/obsidian-keep-headings#3]
Just when I tried the fix in `840b37e`, this need arose.
May be needed in the long run.  
Thanks

**Comment by PlayerMiller109** [comment]
Do you mean like this:

<img width="200" src="https://github.com/user-attachments/assets/82f0c674-1a69-4b84-a580-151dec41fd59">

It's at `d1f7381` just now.
