### ISSUE TITLE
Heading button for editing?

### ISSUE THREAD

**Issue by micaelarealign** [PlayerMiller109/obsidian-keep-headings#5]
It would be amazing if you could make it so there's an option to place a button instead of making it work by clicking directly into the header. I tried to do this myself but failed miserably to get a button to appear beside headings. But I recently found a plugin that managed to add a button beside headings and wondered if it could be adapted for keep headings

https://github.com/skztr/obsidian-plugin-section-copy

**Comment by micaelarealign** [comment]
Sad to hear this isn't planned, but understandable. I would be interested in trying to make my own version/applying this for myself. Do you have even a hint of how I might go about doing that? If you could just point me in the right direction I would be eternally grateful.

**Comment by huachuman** [comment]
+1 from me

**Comment by playermiller109** [comment]
I have seen that the author in the original post is willing to explain the details. Are you not willing to continue communicating with zir? You can just contact zir through Discord or some other way you prefer as ze said.

**Comment by micaelarealign** [comment]
The whole encryption thing and off-github really creeps me out and doesn't make any sense. Github is the perfect place to discuss this. There's no reason to go elsewhere, or on Discord, which is for children tbh. So no thanks.

**Comment by PlayerMiller109** [comment]
Sorry to hear that you’ve had this distressing encounter. It must have been quite unsettling for you. I understand how it might have added to your discomfort.

But do keep in mind that the original author of the project is typically the most knowledgeable person regarding it. They have an in-depth understanding that allows them to provide swift and precise answers to your inquiries.

Perhaps it would be a good idea to directly express your concerns, and ask the original author why they chose not to discuss on GitHub. Maybe the project is so intricate. Or the author believes GitHub Issues are predominantly not intended for technical discussion, and a more attentive communication space is better to address your needs. Things may not be as bad as you imagine, right?

If you feel strongly averse to continuing this interaction, that’s perfectly understandable and completely fine. These days, AI models have remarkable capabilities in analyzing code. You could consider giving them a try. They might offer new ideas and potential solutions.

These are all the things I can come up with for the moment. I hope everything goes well for you.
